% Python Code
% def decryptRSA(y,d,n):
%     return pow(y,d,n)

function [decrypted] = decryptRSA(encrypted, privateKey, modulo)
%DECRYPTRSA: This function takes encrypted text and decryptes it using the
%private decryption key generated by the recipient
%   Input: Encrypted Text, Private key counterpart to public key used for
%   encryption, modulo base used for encryption
%   Output: Plain text decrypted
    decrypted = powermod(encrypted,privateKey,modulo);
end

